CREATE TYPE star_rating AS ENUM ('0','1', '2', '3', '4', '5');

CREATE TABLE movies (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  comments TEXT,
  rating star_rating NOT NULL
)